[package]
name = "eda-place"
version = "0.1.0"
edition = "2021"

[dependencies]
eda-model = { path = "../model" }
serde_json = { workspace = true }
[dev-dependencies]
eda-gates = { path = "../gates" }
eda-router = { path = "../router" }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
