[package]
name = "eda-drc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
eda-model = { path = "../model" }

[dev-dependencies]
serde_yaml = { workspace = true }
eda-kicad = { path = "../kicad" }
eda-engine = { path = "../engine" }
eda-place = { path = "../place" }
eda-freeroute = { path = "../freeroute" }
