//! Ratchet gate: `docs/parity/scores.json` is the harness's own committed
//! record of "how good is this today" (regenerated by
//! `python3 tools/parity_report.py`, which runs the `#[ignore]`d
//! `parity_*` oracle tests and folds their `docs/parity/raw/*.json` output
//! into a flat list of named metrics). This test reads that committed file
//! and asserts every metric's `current` is at or above its recorded
//! `floor` -- nothing here calls kicad-cli or touches the QA corpus, so it
//! runs on every plain `cargo test`, not just the opt-in harness. That's
//! the point: a regression that crept into a *committed* scores.json
//! (hand-edited, or from a stale re-run after a real regression) fails the
//! normal suite, not just an opt-in job someone has to remember to run.
//!
//! This test does not itself measure anything -- re-run
//! `python3 tools/parity_report.py` (needs kicad-cli on PATH) to refresh
//! `current` against live kicad-cli output. Raising a `floor` is a
//! deliberate act (the script never lowers one on its own; see its own
//! doc comment), so this test failing means either a real regression or a
//! `floor` that needs updating by hand once the regression is understood.

use std::path::PathBuf;

fn repo_root() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.parent().and_then(|p| p.parent()).expect("crates/kicad -> repo root").to_path_buf()
}

#[test]
fn scores_meet_their_recorded_floor() {
    let path = repo_root().join("docs/parity/scores.json");
    let Ok(text) = std::fs::read_to_string(&path) else {
        eprintln!("{} not found yet -- run `python3 tools/parity_report.py` (needs kicad-cli) to generate it; nothing to ratchet yet.", path.display());
        return;
    };
    let json: serde_json::Value = serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));
    let metrics = json.get("metrics").and_then(|m| m.as_array()).unwrap_or_else(|| panic!("{}: missing a \"metrics\" array", path.display()));
    assert!(!metrics.is_empty(), "{}: \"metrics\" array is empty", path.display());

    let mut failures = Vec::new();
    for m in metrics {
        let name = m.get("name").and_then(|n| n.as_str()).unwrap_or("<unnamed>").to_string();
        // `"ratchet": false` marks a metric as informational: still
        // reported, never a gate -- see its `note` in scores.json.
        if m.get("ratchet").and_then(|v| v.as_bool()) == Some(false) {
            continue;
        }
        let current = m.get("current").and_then(|v| v.as_f64());
        let floor = m.get("floor").and_then(|v| v.as_f64());
        let (Some(current), Some(floor)) = (current, floor) else {
            // A metric with no data yet (e.g. kicad-cli wasn't available
            // the last time the harness ran) is recorded as null, not
            // zero -- null must never silently read as "0 >= floor fails"
            // nor "absent so skip a real regression". Treat it as
            // not-yet-measured and move on; it is visible in REPORT.md.
            continue;
        };
        // A hair of slack for the float round trip through JSON -- this is
        // a regression gate, not a precision instrument.
        if current < floor - 1e-9 {
            failures.push(format!("{name}: current={current:.4} dropped below floor={floor:.4}"));
        }
    }
    assert!(failures.is_empty(), "parity ratchet failed -- {} metric(s) regressed below their recorded floor:\n{}", failures.len(), failures.join("\n"));
}
