[package]
name = "eda-gates"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
eda-model = { path = "../model" }
eda-engine = { path = "../engine" }
eda-layout = { path = "../layout" }
eda-drc = { path = "../drc" }
eda-lint = { path = "../lint" }

[dev-dependencies]
serde_yaml = { workspace = true }
