// Assign Netclass... on a selection: `pcbnew.EditorControl.assignNetclass` (BOARD_EDITOR_CONTROL::AssignNetclass, pcbnew/tools/
// board_editor_control.cpp) and `eeschema.InteractiveEdit.assignNetclass` (SCH_EDIT_TOOL::AssignNetclass). Both turn the selected
// items into the names of their nets, drop the nets KiCad named itself (`NETINFO_ITEM::HasAutoGeneratedNetname`), say so when none is
// left ("Selection contains no items with labeled nets.") and otherwise open the dialog (components/AssignNetclassDialog.tsx) on them.
import { createElement } from "react";
import { AssignNetclassDialog } from "../components/AssignNetclassDialog";
import { netsOfSelection } from "../kicad-port/boardControl";
import { boardNetNames, hasAutoGeneratedNetname } from "../kicad-port/boardSetupRules";
import { openSweepDialog } from "./pcbSweepDialogs";
import type { SweepCtx } from "./pcbSweepKit";

/** Open the Assign Netclass dialog for `selected` nets (`candidates` are the nets a pattern is tried against); a toast when none of them has a name of its own. */
export function openAssignNetclass(selected: readonly string[], candidates: readonly string[], toast: (message: string, kind: "info" | "error") => void): void {
  const named = selected.filter((n) => !hasAutoGeneratedNetname(n));
  if (named.length === 0) {
    toast("Selection contains no items with labeled nets.", "error");
    return;
  }
  openSweepDialog({ kind: "element", element: createElement(AssignNetclassDialog, { nets: named, candidates }) });
}

/** The board editor's entry: the nets of the selected tracks, vias, zones and footprints' pads (`netsOfSelection`). */
export function registerPcbAssignNetclass(m: Map<string, () => void>, ctx: SweepCtx): void {
  const { state, dispatch } = ctx;
  m.set("pcbnew.EditorControl.assignNetclass", () => {
    if (state.tab !== "pcb" || !state.board) return;
    openAssignNetclass(netsOfSelection(ctx.requestSelection(), state.board), boardNetNames(state.board), (message, kind) => dispatch({ type: "TOAST", message, kind }));
  });
}
