// GENERATED by web/studio/tools/extract-erc-checks.js from KiCad 8303b2ada05226fa603e5ac0420d240fd65ce52b (eeschema/erc/erc_item.cpp and
// eeschema/erc/erc_settings.cpp). Do not edit by hand: run the extractor again.

//! The ERC checks Schematic Setup > Violation Severity lists.

/// `ERC_ITEM::GetItemsWithSeverities()`: the ERC settings keys, in KiCad's order, with the severity `ERC_SETTINGS` gives each when
/// nothing is set. The last one, `pin_to_pin`, is the pin conflicts map's: Ignore or "from the map".
pub const ERC_CHECKS: &[(&str, &str)] = &[
    ("pin_not_connected", "error"),
    ("pin_not_driven", "error"),
    ("power_pin_not_driven", "error"),
    ("no_connect_connected", "warning"),
    ("no_connect_dangling", "warning"),
    ("label_dangling", "error"),
    ("isolated_pin_label", "warning"),
    ("single_global_label", "ignore"),
    ("same_local_global_label", "warning"),
    ("same_local_global_power", "warning"),
    ("wire_dangling", "error"),
    ("bus_entry_needed", "error"),
    ("endpoint_off_grid", "warning"),
    ("four_way_junction", "ignore"),
    ("label_multiple_wires", "warning"),
    ("unconnected_wire_endpoint", "warning"),
    ("duplicate_reference", "error"),
    ("unit_value_mismatch", "error"),
    ("different_unit_footprint", "error"),
    ("different_unit_net", "error"),
    ("duplicate_sheet_names", "error"),
    ("hier_label_mismatch", "error"),
    ("multiple_net_names", "warning"),
    ("bus_definition_conflict", "error"),
    ("bus_to_bus_conflict", "error"),
    ("bus_to_net_conflict", "error"),
    ("net_not_bus_member", "warning"),
    ("ground_pin_not_ground", "warning"),
    ("stacked_pin_name", "warning"),
    ("field_name_whitespace", "warning"),
    ("unannotated", "error"),
    ("unresolved_variable", "error"),
    ("undefined_netclass", "error"),
    ("simulation_model_issue", "ignore"),
    ("similar_labels", "warning"),
    ("similar_power", "warning"),
    ("similar_label_and_power", "warning"),
    ("lib_symbol_issues", "warning"),
    ("lib_symbol_mismatch", "warning"),
    ("footprint_link_issues", "warning"),
    ("footprint_filter", "ignore"),
    ("extra_units", "error"),
    ("missing_unit", "warning"),
    ("missing_input_pin", "warning"),
    ("missing_bidi_pin", "warning"),
    ("missing_power_pin", "error"),
    ("pin_to_pin", "warning"),
];

/// The severity `ERC_SETTINGS` gives `key` when nothing is set, or `None` for a key that is not an ERC check.
pub fn default_severity(key: &str) -> Option<&'static str> {
    ERC_CHECKS.iter().find(|(k, _)| *k == key).map(|(_, s)| *s)
}

/// Whether `key` is one of [`ERC_CHECKS`].
pub fn is_erc_check(key: &str) -> bool {
    default_severity(key).is_some()
}
